### ISSUE TITLE
how do i create command for a specific job like police?

### ISSUE THREAD

**Issue by Kamorak** [Elbarjo/esx_rpchatV5#1]

**Comment by Doublox** [comment]
tu va dans le client et tu fait comme j'ai fait ^^

**Comment by tobipazos25** [comment]
could you explain us? im having the same issue, this is what i tried

`function getIdentity(source)
	local identifier = GetPlayerIdentifiers(source)[1]
	local result = MySQL.Sync.fetchAll("SELECT * FROM users WHERE identifier = @identifier", {['@identifier'] = identifier})
	if result[1] ~= nil then
		local identity = result[1]

		return {
			identifier = identity['identifier'],
			firstname = identity['firstname'],
			lastname = identity['lastname'],
			dateofbirth = identity['dateofbirth'],
			sex = identity['sex'],
			height = identity['height'],
			permission_level = identity['permission_level'],
			job = identity['job']
		}
	else
		return nil
	end
end`

and then these

` RegisterCommand('poli', function(source, args, rawCommand)
    local playerName = GetPlayerName(source)
    local msg = rawCommand:sub(6)
    local name = getIdentity(source)
    if name.job == 'police' then
    	fal = name.firstname .. " " .. name.lastname
    	TriggerClientEvent('chat:addMessage', -1, {
        template = '<div style="padding: 0.5vw; margin: 0.5vw; background-color: rgba(0, 0, 255, 1); border-radius: 3px;"><i class="fas fa-ad"></i>Policia - {0}:<br> {1}<br></div>',
        args = { fal, msg }
    	})
    end
end, false)`
